Algoritmo "vouf"
// Prática do conceito de OPERADORES RELACIONAIS
Var
  n1, n2: inteiro
  resultado1: logico
  resultado2: logico
  resultado3: logico
Inicio
  Escreva ("Digite um número: ")
  Leia (n1)
  Escreva ("Digite um número: ")
  Leia (n2)
  resultado1 <- (n1>n2)
     Escreval ("O PRIMEIRO NÚMERO É MAIOR QUE O SEGUNDO?", resultado1)
     
  resultado2 <- (n1<n2)
     Escreval ("O PRIMEIRO NÚMERO É MENOR QUE O SEGUNDO?", resultado2)
     
  resultado3 <- (n1=n2)
     Escreval ("OS DOIS NÚMEROS SÃO IGUAIS?", resultado3)

Fimalgoritmo