Algoritmo "fazercafe"
  // Função: se/senão
Var
   fazer_cafeteira: logico
Inicio
  Escreval ("Esquentar água")
  Escreval ("Será feito na cafeteira?")
  Leia (fazer_cafeteira)
            se fazer_cafeteira = verdadeiro entao
            Escreval ("Ligar e esquentar na cafeteira")
            senao
            Escreval ("Esquentar no fogo")
            fimse
  Escreval ("Esperar ferver a água")
  Escreval ("Coar o café")
  Escreval ("Servir")
Fimalgoritmo