Algoritmo "nome_idade_cidade"
Var
 nome: caractere
 idade: inteiro
 cidade: caractere
Inicio
  Escreval ("Qual é o seu nome?")
  Leia (nome)
  Escreval ("Prazer em te conhecer,", nome)
  Escreval ("Qual é a sua idade?")
  Leia (idade)
  Escreval ("Você tem", idade, " anos")
  Escreval ("Aonde você mora?")
  Leia (cidade)
  Escreval ("Você mora em ", cidade, ", Gabriel")
Fimalgoritmo