Algoritmo "regressiva"

Var

procedimento ContagemRegressiva()
var
   contador: inteiro
Inicio
contador <- 10
  Enquanto (contador>0) faca
  Escreval (contador,"....................")
           contador <- contador - 1
  fimenquanto


FimProcedimento

Inicio
ContagemRegressiva()
Escreval ("################################")
Escreval ("         FELIZ                  ")
Escreval ("          ANO                   ")
Escreval ("         NOVO!                  ")
Escreval ("********************************")

Fimalgoritmo