Algoritmo "semnome"
// Leia um número e mostre o dobro, o triplo ou a metade
Var
  n, dobro, triplo: inteiro
  metade: real
Inicio
   Escreval ("Digite um número: ")
   Leia (n)
   dobro <- n*2
   Escreval ("O dobro desse número é igual a:", dobro)
   triplo <- n*3
   Escreval ("O triplo desse número é igual a:", triplo)
   metade <- n/2
   Escreval ("A metade desse número é igual a:", metade)
Fimalgoritmo