Algoritmo "operacoes"
// Leia e soma dois números
Var
    n1, n2, s, sb, mt: inteiro
    dv: real
Inicio
 Escreval ("Digite um número:")
 Leia (n1)
 Escreval ("Digite outro número:")
 Leia (n2)
 s <- n1 + n2
 Escreval ("A soma de", n1, " e", n2 , " é igual a:", s )
 sb <- n2 - n1
 Escreval (n1, " menos", n2 , " é igual a:", sb )
 mt <- n1 * n2
 Escreval (n1, " vezes", n2 , " é igual a:", mt )
 dv <- n1 / n2
 Escreval (n1, " dividido por", n2 , " é igual a:", dv )
Fimalgoritmo